### ISSUE TITLE
Header tag

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#20]
Nice use of the nav tag! I would change this first div to a `<header>` though to make it more semantic. It's also strange to have a p tag before your h1. @eadehemingway @shahenazmonia Thoughts? 

https://github.com/fack2/WebRangers-repo/blob/62602c04353f8f7ab3edb365eaacc303f8afbd35/index.html#L21-L30

**Comment by shahenazmonia** [comment]
Yeah right, the header tag should be the first one in the page

**Comment by sulieman1** [comment]
div changed to header, now it should be more semantic.
@jema28 
@shahenazmonia
