### ISSUE TITLE
Section vs divs

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#21]
A section is already a container that replaces the need for a div 😸 

https://github.com/fack2/WebRangers-repo/blob/62602c04353f8f7ab3edb365eaacc303f8afbd35/index.html#L31-L53

**Comment by sulieman1** [comment]
div removed.

**Comment by sulieman1** [comment]
div removed.
@jema28

**Comment by sulieman1** [comment]
div removed.
@jema28

**Comment by sulieman1** [comment]
div removed.
@jema28
