### ISSUE TITLE
Deleting branches after merge

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#23]
Great branch names! It's good to get into the habit of deleting branches as soon as you merge a pull request though. For now, you can delete the branches here: 

<img width="902" alt="Screenshot 2019-06-20 at 09 18 26" src="https://user-images.githubusercontent.com/25960351/59825327-6860b580-933c-11e9-8269-4aee6d2741f5.png">

**Comment by sulieman1** [comment]
Branches deleted!
@jema28
