### ISSUE TITLE
Heading tags: h1 vs h2

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#27]
A note to make sure you don't have more than one h1 in your index.html. The h1 should be the page heading and h2s can be content headings 🌵

**Comment by sulieman1** [comment]
Main heading remained "h1" and the rest of the headings changed to "h2", so now we have one main heading.
@jema28

**Comment by sulieman1** [comment]
Main heading remained "h1" and the rest of the headings changed to "h2", so now we have one main heading.
@jema28
