### ISSUE TITLE
Adding for and id attributes to labels

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#28]
Make sure you add identical for and id attributes to your label (for) and input(id) so they're linked e.g.
```
<label for="name"></label> 
<input id="name"></input> 
```
https://github.com/fack2/WebRangers-repo/blob/62602c04353f8f7ab3edb365eaacc303f8afbd35/index.html#L119-L122

**Comment by sulieman1** [comment]
for attribute of the label element now matches the id attribute of the input element.
@jema28
