### ISSUE TITLE
Classes vs ids in CSS

### ISSUE THREAD

**Issue by jema28** [fack2/WebRangers-repo#29]
When writing selectors, it's best to target classes vs ids. Generally, ids should just be used for javascript. Have a look at this reference for more info: https://dev.to/claireparkerjones/reasons-not-to-use-ids-in-css-4ni4. 

https://github.com/fack2/WebRangers-repo/blob/8ccede59f4d9b2e359f4cd1464976b2d7db1cb8b/style.css#L7-L17

**Comment by sulieman1** [comment]
ID's changed to Classes
@jema28
